
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bagus Perdana
 */
public class frmutama extends javax.swing.JFrame {

    frmutama(FUpdateMahasiswa aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form frmutama
     */
    
    
    public void tampildata()
    {
     Database db = new Database();
     mahasiswaTableModel tabelmahasiswa = new mahasiswaTableModel();
     tabelmahasiswa.setData(db.tampil_semua_mahasiswa());
     JTable.setModel(tabelmahasiswa);
    }
    
    
    public frmutama() {
        initComponents();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        TblTambah = new javax.swing.JButton();
        TblEdit = new javax.swing.JButton();
        TblHapus = new javax.swing.JButton();
        TblRefresh = new javax.swing.JButton();
        TblCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengelolaan Data Mahasiswa");
        setResizable(false);

        jLabel1.setText("PENGOLAHAN DATA MAHASISWA");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTable);

        TblTambah.setText("Tambah");
        TblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblTambahActionPerformed(evt);
            }
        });

        TblEdit.setText("Edit");
        TblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblEditActionPerformed(evt);
            }
        });

        TblHapus.setText("Hapus");
        TblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblHapusActionPerformed(evt);
            }
        });

        TblRefresh.setText("Refresh");
        TblRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblRefreshActionPerformed(evt);
            }
        });

        TblCari.setText("Cari");
        TblCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TblEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TblCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TblRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addComponent(TblHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TblTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TblTambah)
                        .addGap(18, 18, 18)
                        .addComponent(TblEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TblHapus)
                        .addGap(18, 18, 18)
                        .addComponent(TblRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(TblCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public FTambahMahasiswa formtambah;
    Database db = new Database();
    mahasiswaTableModel tabelmahasiswa = new mahasiswaTableModel();
   
    
    private void TblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblTambahActionPerformed
        // TODO add your handling code here:
        
        //buat form
        formtambah = new FTambahMahasiswa(this);
        formtambah.setVisible(true);
        formtambah.tnim.setText("");
        formtambah.tnama.setText("");
        formtambah.tjk.setText("");
        formtambah.ttinggi.setText("");
        //refreshdata(); (dibuat perubahan karena tidak berfungsi)
        refreshdata();
    }//GEN-LAST:event_TblTambahActionPerformed

    
    
    public void refreshdata()
    {
         tabelmahasiswa.setData(db.tampil_semua_mahasiswa());
         tabelmahasiswa.fireTableDataChanged();
         tampildata();
         JTable.changeSelection(0, 0, false, false);
    }

    
    private void TblRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblRefreshActionPerformed
        // TODO add your handling code here:
        
        //panggil method
        refreshdata();
    }//GEN-LAST:event_TblRefreshActionPerformed

   
    private void TblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblHapusActionPerformed
        // TODO add your handling code here:

        //deteksi kursor berada dibaris keberapa
        try
        {
        int baris = JTable.getSelectedRow();
        String nim = (String)tabelmahasiswa.getValueAt(baris, 0);
        String nama = (String)tabelmahasiswa.getValueAt(baris, 1);
        Object[] pilihan = {"Ya","Tidak"};
        int jawaban = JOptionPane.showOptionDialog(null,"Anda Yakin Data "
        + "Mahasiswa Dengan NIM " +nim+" Dengan Nama "+nama+" Akan "
        + "Dihapus ?","Peringatan",JOptionPane.DEFAULT_OPTION,
        JOptionPane.WARNING_MESSAGE,null,pilihan,pilihan[0]);
        
        if(jawaban == 0)
        {
            db.hapus_mahasiswa(nim);
            refreshdata();
     
        }
        }
        catch (ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Ingin Dihapus!!!");
        }    
        
    }//GEN-LAST:event_TblHapusActionPerformed

    private void TblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblEditActionPerformed
        // TODO add your handling code here:
        FUpdateMahasiswa formupdate = new FUpdateMahasiswa(this);
       
       //lakukan pengecekan data berdasarkan pilihan kursor
       int baris = JTable.getSelectedRow();
       String nim = (String)tabelmahasiswa.getValueAt(baris,0);
       mahasiswa m = db.pilih_mahasiswa(nim);
       
       if(m!=null)
       {
           formupdate.setForm(m);
           formupdate.setVisible(true);
           refreshdata();
       }
       else
       {
         JOptionPane.showMessageDialog(null, "Mahasiswa dengan NIM "+nim
               +" Tidak Ditemukan ");
       }
       
    }//GEN-LAST:event_TblEditActionPerformed

    private void TblCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblCariActionPerformed
        // TODO add your handling code here:
        String katakunci;
        katakunci=JOptionPane.showInputDialog(null,"Nama Mahasiswa yang dicari ? "
                ,"Filter/Pencarian",JOptionPane.QUESTION_MESSAGE);
        if(katakunci!=null)
        {
            tabelmahasiswa.setData(db.filter_mahasiswa(katakunci));
            tabelmahasiswa.fireTableDataChanged();
        }
    }//GEN-LAST:event_TblCariActionPerformed

    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmutama().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton TblCari;
    private javax.swing.JButton TblEdit;
    private javax.swing.JButton TblHapus;
    private javax.swing.JButton TblRefresh;
    private javax.swing.JButton TblTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
